### ISSUE TITLE
Shrani in odpri?

### ISSUE THREAD

**Issue by andrejbauer** [julijatominc/programiranje2_crnobelo#8]
A resno mislita spravljati igre na v datoteke? Vajin menu ima izibri "shrani" in "odpri".

**Comment by julijatominc** [comment]
Funkcijo bi rada ohranila, zanima me, ali to ni predvideno za naš projekt ali je napačno to, da shranjujemo v datoteko?

**Comment by andrejbauer** [comment]
_Zakaj_ boste shranjevali v datoteko? A bodo igralci eno igro igrali en teden in bodo vmes shranjevali igro v datoteko?

**Comment by SeverinMejak** [comment]
Zdi se nama, da je boljše, če ima uporabnik več možnosti. Da če bi kdo slučajno želel shraniti igro v datoteko, da ima tudi to možnost. Drugi vidik shranjevanja je, da ta projekt služi kot modelni projekt za morebitne projekte v prihodnosti, kjer bi bilo shranjevanje bolj smiselno.

**Comment by andrejbauer** [comment]
Ok, v tem primeru si morda oglejta [pickle](https://docs.python.org/3.4/library/pickle.html), ki go za vaju shranil poljuben objekt v datoteko in ga prebral nazaj.
