### ISSUE TITLE
Kaj je `Python_Projekt_verzija_2.py`

### ISSUE THREAD

**Issue by andrejbauer** [julijatominc/programiranje2_crnobelo#9]
Glavni razlog, da vas silim v uporabo `Git` je točno ta, da ne boste počeli tega: http://tapastic.com/episode/34391

Git ima verzije, veje, lahko se primakata naprej in nazaj, res ni nobene potrebe, da delata z git potem pa za povrh še na roke kopirata naokoli datoteke in jim dajeta čudna imena.

Use the Git, Luke!

**Comment by julijatominc** [comment]
Python_projekt_verzija_2 ima tako ime, ker je kopija datoteke, ki jo je Severin Mejak pripravil za predmet Uvod v programiranje, kjer je objavil dve verziji, verzija 2 je boljša, zato sva skopirala to.

To sva zapisala sedaj zapisala tudi v readme. 
Ali bi jo bilo mogoče bolj odstraniti?

**Comment by julijatominc** [comment]
Python_projekt_verzija_2 ima tako ime, ker je kopija datoteke, ki jo je Severin Mejak pripravil za predmet Uvod v programiranje, kjer je objavil dve verziji, verzija 2 je boljša, zato sva skopirala to.

Sedaj sva dodala opis še v readme.
Ali menite, da je datoteka moteča in bi jo bilo bolje odstraniti?
(Po nesreci sem ponovno odprla issue...)

**Comment by andrejbauer** [comment]
Aha, ok, v tem primeru bi rekel, da se recimo naredi ena mapa `krama` ali kaj takega in se tja tlači zadeve, ki niso dejanska koda od projekta. Ampak pri tako majhnem projektu to ni pomembno in je precej vseeno, kaj delata. Mene je zaskrbleo, da delata "verzije na roko" tako, da kopirata naokoli skoraj enake različice iste datoteke in jim potem dajeta imena "verzija1", "verzija2" itd. Ravno temu se izogibamo z uporabo git.
